Run pip-compile.
airflowdocker/airflow-docker pull request #33
Opened 2020-11-09 17:24 UTC by gordonfierce

2020-11-09 17:54 UTC, huntcsg approved these changes
lgtm.

2020-11-09 18:00 UTC, huntcsg requested changes
Actually, it doesn't seem to be correct :(

2020-11-13 15:25 UTC, danielnazareth89 approved these changes

2020-11-13 16:02 UTC, huntcsg approved these changes

2020-11-13 16:03 UTC, merged